### ISSUE TITLE
Fails when disk is full

### ISSUE THREAD

**Issue by Miladiir** [sindresorhus/empty-trash-cli#2]
When the disk is completely full, empty-trash fails:

```
➜  ~  empty-trash 
/usr/local/lib/node_modules/empty-trash-cli/node_modules/configstore/index.js:62
                throw err;
                ^

Error: ENOSPC: no space left on device, open '/Users/miladiir/.config/configstore/update-notifier-empty-trash-cli.json.e79ade0c26640f33324fbdff019d6317'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1161:15)
    at Function.writeFileSync [as sync] (/usr/local/lib/node_modules/empty-trash-cli/node_modules/write-file-atomic/index.js:37:12)
    at Object.create.all.set (/usr/local/lib/node_modules/empty-trash-cli/node_modules/configstore/index.js:55:21)
    at Object.Configstore (/usr/local/lib/node_modules/empty-trash-cli/node_modules/configstore/index.js:20:11)
    at new UpdateNotifier (/usr/local/lib/node_modules/empty-trash-cli/node_modules/update-notifier/index.js:34:17)
    at module.exports (/usr/local/lib/node_modules/empty-trash-cli/node_modules/update-notifier/index.js:123:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/empty-trash-cli/cli.js:13:1)
    at Module._compile (module.js:435:26)
```

Rather amusing if you ask me :grin:

**Comment by sindresorhus** [comment]
Well yeah, nothing will work correctly when your disk is full. Not much I can or care to do about that.
